# Generated by Django 3.1 on 2023-10-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('random_url', models.CharField(max_length=10, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
