# Generated by Django 4.2.6 on 2023-11-01 03:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_project_branch_name_remove_project_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='random_url',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
